import {
  AnamnesisCategoryDefaults,
  AnamnesisJsonExample,
  AnamnesisSchema,
  type Anamnesis,
  type AnamnesisCategory,
} from "@/models/Anamnesis.js";
import type { Language } from "@/models/Language.js";
import {
  buildPrompt,
  getCreativeLLM,
  getDeterministicLLM,
  handleLangchainError,
} from "@/utils/llm.js";
import z from "zod";
import type { Inconsistency } from "@/models/Inconsistency.js";
import type { Diagnosis } from "@/models/Diagnosis.js";
import { HumanMessage, SystemMessage } from "langchain";
import { retry } from "@/utils/retry.js";
import type { Case } from "@/models/Case.js";
import { emitTrace } from "@/utils/tracing.js";
import type { Symptom } from "@/models/Symptom.js";

export async function generateAnamnesisFromOutline(
  diagnosis: Diagnosis, // provided by the user
  outline: string,
  userInstructions?: string, // provided by the user
  anamnesisCategories:
    | AnamnesisCategory[]
    | undefined = AnamnesisCategoryDefaults, // provided by the user
  previousCase?: Case, // generated by a previous chain step
  inconsistencies?: Inconsistency[] // generated by a previous chain step
): Promise<Anamnesis> {
  const fixingMode = !!previousCase && !!inconsistencies?.length;
  const systemPrompt = buildPrompt(
    `You are an AI generating data for a medical training simulator. Your current task is to generate the Anamnesis (medical history) based on the provided Case Outline.`,

    fixingMode
      ? `The previous JSON generation contained inconsistencies. Regenerate the JSON, fixing the following issues while maintaining the patient's voice:

Original Anamnesis:
${JSON.stringify({ anamnesis: previousCase.anamnesis })}

Inconsistencies to Fix:
${inconsistencies.map((i, idx) => `${idx + 1}. [Severity ${i.severity}] ${i.description}\n   Suggested Fix: ${i.suggestion}`).join("\n")}`
      : `Generate the anamnesis fields from scratch based on the approved outline.`,

    `Return ONLY a valid JSON object matching the requested categories.
Schema:
${JSON.stringify({ anamnesis: AnamnesisJsonExample() })}`,

    `Requirements:
- The text inside the JSON must be written from the perspective of the PATIENT filling out an intake form.
- Use the patient's subjective voice, layman's terms, and personal tone (e.g., "My chest feels heavy" instead of "Patient presents with angina").
- Adapt the tone to fit the patient's age and demographic as defined in the outline.
- Return ONLY the JSON object, no additional text like prefix or suffix.`
  );

  const userPrompt = buildPrompt(
    `Target Diagnosis: ${diagnosis.name} ${diagnosis.icd ?? ""}`,

    `Case Outline: ${outline}`,

    anamnesisCategories
      ? `Required Intake Form Categories to fill: ${anamnesisCategories.join(", ")}`
      : `Use standard patient intake categories (e.g., Current Symptoms, Past Illnesses, Family History, Lifestyle/Habits, Current Medications).`,

    userInstructions
      ? `Additional Instructions: ${userInstructions}`
      : undefined
  );

  console.debug(
    `[GenerateAnamnesisFromOutline] Prompt:\n${systemPrompt}\n${userPrompt}`
  );

  // Initialize cases to empty in case of failure
  try {
    const AnamnesisSchemaWrapper = z.object({
      anamnesis: AnamnesisSchema.describe("Generated anamnesis"),
    });

    const anamnesis: Anamnesis = await retry(
      async (attempt: number, previousError?: Error) => {
        const result = await getCreativeLLM()
          .withStructuredOutput(AnamnesisSchemaWrapper)
          .invoke([
            new SystemMessage(systemPrompt),
            new HumanMessage(
              userPrompt +
                (previousError
                  ? `\nPrevious generation error: ${previousError.message}`
                  : "")
            ),
          ])
          .catch((error) => {
            handleLangchainError(error);
          });

        console.debug(
          `[GenerateAnamnesisFromOutline] [Attempt ${attempt}] LLM raw Response:\n`,
          JSON.stringify(result)
        );

        return result.anamnesis;
      },
      2,
      0,
      (error, attempt) => {
        emitTrace(
          `[GenerateAnamnesisFromOutline] Attempt ${attempt} failed with error: ${error.message}`,
          { category: "error" }
        );
      }
    );

    return anamnesis;
  } catch (error) {
    console.error(`[GenerateAnamnesisFromOutline] Error:`, error);
    throw error;
  }
}

export async function generateAnamnesisCoT(
  diagnosis: Diagnosis,
  symptoms: Symptom[],
  relatedCase?: Case,
  userInstructions?: string,
  anamnesisCategories:
    | AnamnesisCategory[]
    | undefined = AnamnesisCategoryDefaults
): Promise<string> {
  const systemPrompt = `You are a patient with these symptoms: 
${symptoms.map((s) => s.name).join(", ")}
Generate a step by step reasoning process ${anamnesisCategories ? "to answer the provided anamnesis categories." : "to generate an anamnesis."}
Return the steps as a list of steps in markdown format.
${
  relatedCase
    ? `The patient case has the following properties which might be relevant for the anamnesis generation:
  ${JSON.stringify(relatedCase)}`
    : ""
}`;

  const userPrompt = [
    `Provided Diagnosis: ${diagnosis.name} ${diagnosis.icd ?? ""}`,
    userInstructions
      ? `Additional provided instructions: ${userInstructions}`
      : "",
    anamnesisCategories
      ? `Provided anamnesis categories: ${anamnesisCategories.join(", ")}`
      : "",
  ]
    .filter((s) => s.length > 0)
    .join("\n");

  console.debug(
    `[GenerateAnamnesisCoT] Prompt:\n${systemPrompt}\n${userPrompt}`
  );

  try {
    const stepsString: string = await retry(
      async (attempt: number) => {
        const text = await getDeterministicLLM({ outputFormat: "text" })
          .invoke([
            new SystemMessage(systemPrompt),
            new HumanMessage(userPrompt),
          ])
          .catch((error) => {
            handleLangchainError(error);
          });
        console.debug(
          `[GenerateAnamnesisCoT] [Attempt ${attempt}] LLM raw Response:\n`,
          text
        );

        return text.text;
      },
      2,
      0,
      (error, attempt) => {
        emitTrace(
          `[GenerateAnamnesisCoT] Attempt ${attempt} failed with error: ${error.message}`,
          { category: "error" }
        );
      }
    );

    return stepsString;
  } catch (error) {
    console.error(`[GenerateAnamnesisCoT] Error:`, error);
    throw error;
  }
}

export async function generateAnamnesisOneShot(
  diagnosis: Diagnosis, // provided by the user
  symptoms: Symptom[], // generate by a chain step
  relatedCase?: Case, // generated by a previous chain step
  cot?: string, // generated by a previous chain step
  userInstructions?: string, // provided by the user
  anamnesisCategories:
    | AnamnesisCategory[]
    | undefined = AnamnesisCategoryDefaults, // provided by the user
  inconsistencies?: Inconsistency[] // generated by a previous chain step
): Promise<Anamnesis> {
  const { anamnesis: previousAnamnesis, ...caseWithoutAnamnesis } =
    relatedCase ?? {};
  const systemPrompt = `You are a patient with these symptoms: 
${symptoms.map((s) => s.name).join(", ")}
Generate an anamnesis ${anamnesisCategories ? "answering the provided categories based on your symptoms." : "answering standard anamnesis categories."}
${cot ? `Think step by step:\n${cot}` : ""}
${
  Object.keys(caseWithoutAnamnesis).length > 0
    ? `The patient case has the following properties which might be relevant for the anamnesis generation:
  ${JSON.stringify(caseWithoutAnamnesis)}`
    : ""
}
${
  previousAnamnesis
    ? `Try to fix the inconsistencies from the previous anamnesis generated:\n${JSON.stringify({ anamnesis: previousAnamnesis })}
with inconsistencies:
${inconsistencies
  ?.map((i, idx) => {
    return `${idx + 1}. severity ${i.severity}: ${i.description}
suggested fix: ${i.suggestion}`;
  })
  .join("\n")}`
    : ``
}
Return your response in JSON with the provided anamnesis categories
${JSON.stringify({ anamnesis: AnamnesisJsonExample() })}

Requirements:
- Be medically accurate and realistic
- Use standard medical terminology
- Return ONLY the JSON object, no additional text`;

  const userPrompt = [
    `Provided Diagnosis: ${diagnosis.name} ${diagnosis.icd ?? ""}`,
    userInstructions
      ? `Additional provided instructions: ${userInstructions}`
      : "",
    anamnesisCategories
      ? `Provided anamnesis categories: ${anamnesisCategories.join(", ")}`
      : "",
  ]
    .filter((s) => s.length > 0)
    .join("\n");

  console.debug(
    `[GenerateAnamnesisOneShot] Prompt:\n${systemPrompt}\n${userPrompt}`
  );

  // Initialize cases to empty in case of failure
  try {
    const AnamnesisSchemaWrapper = z.object({
      anamnesis: AnamnesisSchema.describe("Generated anamnesis"),
    });

    const anamnesis: Anamnesis = await retry(
      async (attempt: number) => {
        const result = await getCreativeLLM()
          .withStructuredOutput(AnamnesisSchemaWrapper)
          .invoke([
            new SystemMessage(systemPrompt),
            new HumanMessage(userPrompt),
          ])
          .catch((error) => {
            handleLangchainError(error);
          });

        console.debug(
          `[GenerateAnamnesisOneShot] [Attempt ${attempt}] LLM raw Response:\n`,
          JSON.stringify(result)
        );

        return result.anamnesis;
      },
      2,
      0,
      (error, attempt) => {
        emitTrace(
          `[GenerateAnamnesisOneShot] Attempt ${attempt} failed with error: ${error.message}`,
          { category: "error" }
        );
      }
    );

    return anamnesis;
  } catch (error) {
    console.error(`[GenerateAnamnesisOneShot] Error:`, error);
    throw error;
  }
}

/**
 * Translates anamnesis categories from a provided language to English, using a combination of repository lookups and LLM generation for missing translations.
 * @param categories the anamnesis categories to translate to English
 * @param language the source language of the provided categories
 * @returns a record mapping the provided categories to their English translations
 */
export async function generateAnamnesisCategoriesToEnglish(
  categories: AnamnesisCategory[],
  language: Language
): Promise<Record<AnamnesisCategory, AnamnesisCategory>> {
  const systemPrompt = `Translate the provided anamnesis categories from the provided language to English:

Return the categories mapped to their translated part in a JSON
{
  "provided category1": "translated category1",
  "provided category2": "translated category2",
  ...
}`;

  const userPrompt = `Source language: ${language}
Categories to translate:
${categories.join("\n")}`;

  console.debug(
    `[Anamnesis Service] Generating anamnesis category translations with prompt: 
${systemPrompt}
${userPrompt}`
  );

  const prompt = [
    { role: "system", content: systemPrompt },
    { role: "user", content: userPrompt },
  ];

  const response = await getDeterministicLLM().invoke(prompt);

  console.debug(
    "[Anamnesis Service] Generated anamnesis category translations:",
    response.text
  );

  const responseSchema = z.record(z.string(), z.string());
  const parsed = responseSchema.parse(JSON.parse(response.text));

  // Filter only the requested categories
  const result: Record<AnamnesisCategory, AnamnesisCategory> = {};
  for (const [original, translated] of Object.entries(parsed)) {
    if (categories.includes(original as AnamnesisCategory)) {
      result[original as AnamnesisCategory] = translated as AnamnesisCategory;
    }
  }

  if (Object.keys(result).length !== categories.length) {
    throw new Error(
      "Not all categories were translated successfully to English."
    );
  }

  return result;
}

/**
 * Generates translations of anamnesis categories from English to a target language using an LLM.
 * @param categories the anamnesis categories in English to translate
 * @param language the target language to translate the categories into
 * @returns a record mapping English categories to their translations in the target language
 */
export async function generateAnamnesisCategoriesFromEnglish(
  categories: AnamnesisCategory[],
  language: Language
): Promise<Record<AnamnesisCategory, AnamnesisCategory>> {
  const systemPrompt = `Translate the provided anamnesis categories from English to a target language:

Return the categories mapped to their translated part in a JSON
{
  "provided category1": "translated category1",
  "provided category2": "translated category2",
  ...
}`;

  const userPrompt = `Target language: ${language}
Categories to translate:
${categories.join("\n")}`;

  console.debug(
    `[Anamnesis Service] Generating anamnesis category translations with prompt: 
${systemPrompt}
${userPrompt}`
  );

  const prompt = [
    { role: "system", content: systemPrompt },
    { role: "user", content: userPrompt },
  ];

  const response = await getDeterministicLLM().invoke(prompt);

  console.debug(
    "[Anamnesis Service] Generated anamnesis category translations:",
    response.text
  );

  const responseSchema = z.record(z.string(), z.string());
  const parsed = responseSchema.parse(JSON.parse(response.text));

  // Filter only the requested categories
  const result: Record<AnamnesisCategory, AnamnesisCategory> = {};
  for (const [original, translated] of Object.entries(parsed)) {
    if (categories.includes(original as AnamnesisCategory)) {
      result[original as AnamnesisCategory] = translated as AnamnesisCategory;
    }
  }

  if (Object.keys(result).length !== categories.length) {
    throw new Error(
      `Not all categories were translated successfully to ${language}.`
    );
  }

  return result;
}
