import type { Case } from "@/models/Case.js";
import type { Diagnosis } from "@/models/Diagnosis.js";
import type { Inconsistency } from "@/models/Inconsistency.js";
import {
  PatientJsonExample,
  PatientSchema,
  type Patient,
} from "@/models/Patient.js";
import {
  buildPrompt,
  getCreativeLLM,
  handleLangchainError,
} from "@/utils/llm.js";
import { retry } from "@/utils/retry.js";
import { emitTrace } from "@/utils/tracing.js";
import { HumanMessage, SystemMessage } from "langchain";

export async function generatePatientFromOutline(
  diagnosis: Diagnosis, // provided by the user
  outline: string,
  userInstructions?: string, // provided by the user
  previousCase?: Case, // generated by a previous chain step
  inconsistencies?: Inconsistency[] // generated by a previous chain step
): Promise<Patient> {
  const fixingMode = !!previousCase && !!inconsistencies?.length;
  const systemPrompt = buildPrompt(
    `You are an expert medical educator authoring a realistic clinical patient file for a medical training simulator. Your current task is to generate the Patient Demographics based on the provided Case Outline.`,

    fixingMode
      ? `The previous JSON generation contained clinical or logical inconsistencies. Regenerate the JSON, fixing the following issues:

Original Patient:
${JSON.stringify({ patient: previousCase.patient })}

Inconsistencies to Fix:
${inconsistencies.map((i, idx) => `${idx + 1}. [Severity ${i.severity}] ${i.description}\n   Suggested Fix: ${i.suggestion}`).join("\n")}`
      : `Generate the patient information from scratch based on the approved outline.`,

    `Return ONLY a valid JSON object matching the schema below.
Schema:
${JSON.stringify(PatientJsonExample())}`,

    `Requirements:
- Epidemiology: The demographics (Age, Gender, Race) MUST logically align with the typical epidemiology of the Target Diagnosis unless the outline specifies otherwise.
- Biometrics: Ensure Height (in cm) and Weight (in kg) produce a realistic BMI that is clinically appropriate for the patient's presentation and diagnosis.
- Generate a realistic, culturally appropriate full name based on the chosen demographics.
- Return ONLY the JSON object, no additional text like prefix or suffix.`
  );

  const userPrompt = buildPrompt(
    `Target Diagnosis: ${diagnosis.name} ${diagnosis.icd ?? ""}`,

    `Case Outline: ${outline}`,

    userInstructions
      ? `Additional Instructions: ${userInstructions}`
      : undefined
  );

  console.debug(
    `[GeneratePatientFromOutline] Prompt:\n${systemPrompt}\n${userPrompt}`
  );

  try {
    const patient: Patient = await retry(
      async (attempt: number, previousError?: Error) => {
        const result = await getCreativeLLM()
          .withStructuredOutput(PatientSchema)
          .invoke([
            new SystemMessage(systemPrompt),
            new HumanMessage(
              userPrompt +
                (previousError
                  ? `\nPrevious generation error: ${previousError.message}`
                  : "")
            ),
          ])
          .catch((error) => {
            handleLangchainError(error);
          });

        console.debug(
          `[GeneratePatientFromOutline] [Attempt ${attempt}] LLM raw Response:\n`,
          JSON.stringify(result)
        );

        return result;
      },
      2,
      0,
      (error, attempt) => {
        emitTrace(
          `[GeneratePatientFromOutline] Attempt ${attempt} failed with error: ${error.message}`,
          { category: "error" }
        );
      }
    );

    return patient;
  } catch (error) {
    console.error(`[GeneratePatientFromOutline] Error:`, error);
    throw error;
  }
}
