import type { Diagnosis } from "@/models/Diagnosis.js";
import {
  PatientJsonExample,
  PatientSchema,
  type Patient,
} from "@/models/Patient.js";
import {
  buildPrompt,
  getCreativeLLM,
  getDeterministicLLM,
  handleLangchainError,
} from "@/utils/llm.js";
import { retry } from "@/utils/retry.js";
import type { RequestContext } from "@/utils/context.js";
import { HumanMessage, SystemMessage } from "langchain";
import type { Symptom } from "@/models/Symptom.js";
import type { Case } from "@/models/Case.js";
import type { Inconsistency } from "@/models/Inconsistency.js";

export async function generatePatientCoT(
  diagnosis: Diagnosis, // provided by the user
  symptoms: Symptom[], // generated by a previous chain step
  userInstructions?: string, // provided by the user | undefined
  context?: RequestContext
): Promise<string> {
  const systemPrompt = buildPrompt(
    `You are an expert medical educator specializing in designing realistic clinical mock cases for medical students. 
Your task is to generate a step-by-step logical reasoning process (Chain of Thought) detailing EXACTLY HOW to construct the Patient Demographics`,

    `The following symptoms are typical for the diagnosis. You may use a subset of them:
${symptoms.map((s, idx) => `${idx + 1}. ${s.name}: ${s.description ?? ""}`).join("\n")}`,

    `Instructions:
1. DO NOT generate the actual patient data yet. Only generate the thinking process which should be specific to the given diagnosis and a subset of symptoms.
2. Outline a sequential thought process.
3. Output ONLY the numbered reasoning steps, without any conversational filler.`
  );

  const userPrompt = buildPrompt(
    `Target Diagnosis: ${diagnosis.name} ${diagnosis.icd ?? ""}`,

    userInstructions
      ? `Additional Instructions: ${userInstructions}`
      : undefined
  );

  console.debug(
    `[GeneratePatientCoT] SystemPrompt:\n${systemPrompt}\nUserPrompt:\n${userPrompt}`
  );

  try {
    const stepsString: string = await retry(
      async (attempt: number) => {
        const result = await getDeterministicLLM({
          ...context?.llmConfig,
          outputFormat: "text",
        })
          .invoke([
            new SystemMessage(systemPrompt),
            new HumanMessage(userPrompt),
          ])
          .catch((error) => {
            handleLangchainError(error);
          });
        console.debug(
          `[GeneratePatientCoT] [Attempt ${attempt}] LLM raw Response:\n`,
          result.text
        );

        return result.text;
      },
      2,
      0,
      (error, attempt) => {
        const msg = `[GeneratePatientCoT] Attempt ${attempt} failed with error: ${error.message}`;
        console.error(msg);
        context?.traceUtils?.emitTrace(msg, { category: "error" });
      }
    );

    return stepsString;
  } catch (error) {
    console.error(`[GeneratePatientCoT] Error:`, error);
    throw error;
  }
}

export async function generatePatient(
  diagnosis: Diagnosis, // provided by the user
  config:
    | {
        cot: string;
        symptoms: Symptom[];
      }
    | {
        outline: string;
      }
    | {
        case: Case;
        inconsistencies: Inconsistency[];
      },
  userInstructions?: string, // provided by the user | undefined
  context?: RequestContext
): Promise<Patient> {
  const systemPrompt = buildPrompt(
    `You are an expert medical educator authoring a realistic clinical patient file for a medical training simulator.
Your current task is to generate the Patient Demographics ${"outline" in config ? "based on the provided Case Outline." : ""}`,

    "cot" in config
      ? `The following symptoms are typical for the diagnosis. You may use a subset of them:
      ${config.symptoms.map((s, idx) => `${idx + 1}. ${s.name}: ${s.description ?? ""}`).join("\n")}

Think step by step:
    ${config.cot}`
      : undefined,

    "outline" in config
      ? `Generate the patient demographics from scratch based on the approved outline.`
      : undefined,

    "inconsistencies" in config
      ? `The previous JSON generation contained clinical or logical inconsistencies. Regenerate the JSON, fixing the following issues:

Original Patient:
${JSON.stringify({ patient: config.case.patient })}

Inconsistencies to Fix:
${config.inconsistencies.map((i, idx) => `${idx + 1}. [Severity ${i.severity}] ${i.description}\n   Suggested Fix: ${i.suggestion}`).join("\n")}`
      : undefined,

    `Return ONLY a valid JSON object matching the schema below.
Schema:
${JSON.stringify(PatientJsonExample())}`,

    `Requirements:
- Epidemiology: The demographics (Age, Gender, Race) MUST logically align with the typical epidemiology of the Target Diagnosis unless the outline specifies otherwise.
- Biometrics: Ensure Height (in cm) and Weight (in kg) produce a realistic BMI that is clinically appropriate for the patient's presentation and diagnosis.
- Generate a realistic, culturally appropriate full name based on the chosen demographics.
- Return ONLY the JSON object, no additional text like prefix or suffix.`
  );

  const userPrompt = buildPrompt(
    `Target Diagnosis: ${diagnosis.name} ${diagnosis.icd ?? ""}`,

    "outline" in config ? `Case Outline: ${config.outline}` : undefined,

    userInstructions
      ? `Additional Instructions: ${userInstructions}`
      : undefined
  );

  console.debug(
    `[GeneratePatientFromOutline] SystemPrompt:\n${systemPrompt}\nUserPrompt:\n${userPrompt}`
  );

  try {
    const patient: Patient = await retry(
      async (attempt: number, previousError?: Error) => {
        const result = await getCreativeLLM(context?.llmConfig)
          .withStructuredOutput(PatientSchema)
          .invoke([
            new SystemMessage(systemPrompt),
            new HumanMessage(
              userPrompt +
                (previousError
                  ? `\nPrevious generation error: ${previousError.message}`
                  : "")
            ),
          ])
          .catch((error) => {
            handleLangchainError(error);
          });

        console.debug(
          `[GeneratePatientFromOutline] [Attempt ${attempt}] LLM raw Response:\n`,
          JSON.stringify(result, null, 2)
        );

        return result;
      },
      2,
      0,
      (error, attempt) => {
        const msg = `[GeneratePatientFromOutline] Attempt ${attempt} failed with error: ${error.message}`;
        console.error(msg);
        context?.traceUtils?.emitTrace(msg, { category: "error" });
      }
    );

    return patient;
  } catch (error) {
    console.error(`[GeneratePatientFromOutline] Error:`, error);
    throw error;
  }
}
