import type { Language } from "@/models/Language.js";
import type { Procedure } from "@/models/Procedure.js";
import { retry } from "@/utils/retry.js";
import z from "zod";
import {
  buildPrompt,
  getCreativeLLM,
  getDeterministicLLM,
  handleLangchainError,
} from "@/utils/llm.js";
import type { Case } from "@/models/Case.js";
import type { Diagnosis } from "@/models/Diagnosis.js";
import type { Inconsistency } from "@/models/Inconsistency.js";
import {
  PredefinedProcedures,
  ProcedureGenerationArrayJsonExampleString,
  ProcedureGenerationSchema,
  type ProcedureGeneration,
} from "@/models/Procedure.js";
import type { Symptom } from "@/models/Symptom.js";
import { HumanMessage, SystemMessage } from "langchain";
import { emitTrace } from "@/utils/tracing.js";

export async function generateProceduresFromOutline(
  diagnosis: Diagnosis, // provided by the user
  outline: string,
  userInstructions?: string, // provided by the user
  procedureList: Procedure[] | undefined = PredefinedProcedures,
  previousCase?: Case, // generated by a previous chain step
  inconsistencies?: Inconsistency[] // generated by a previous chain step
): Promise<ProcedureGeneration[]> {
  const fixingMode = !!previousCase && !!inconsistencies?.length;
  const systemPrompt = buildPrompt(
    `You are an expert attending physician designing the diagnostic workup for a medical training simulator. Your current task is to order the required Procedures based on the provided Case Outline.`,

    fixingMode
      ? `The previous JSON generation contained clinical or logical inconsistencies. Regenerate the JSON, fixing the following issues while maintaining a realistic diagnostic pathway:

Original Procedures:
${JSON.stringify({ procedures: previousCase.procedures })}

Inconsistencies to Fix:
${inconsistencies.map((i, idx) => `${idx + 1}. [Severity ${i.severity}] ${i.description}\n   Suggested Fix: ${i.suggestion}`).join("\n")}`
      : `Generate the procedures from scratch based on the approved outline.`,

    procedureList?.length
      ? `[RESTRICTED WORKUP]
You MUST ONLY select the necessary diagnostic procedures from the following approved list. Do not invent or recommend any procedures that are not explicitly listed below:
${procedureList.map((p) => `- ${p.name}`).join("\n")}`
      : `Generate a realistic list of standard procedures that should be performed to appropriately work up the patient and confirm the diagnosis.`,

    `Return ONLY a valid JSON object matching the schema below.
Schema:
${`{ "procedures": ${ProcedureGenerationArrayJsonExampleString()} }`}`,

    `Requirements:
- Workup Logic: The procedures must represent a realistic, standard-of-care diagnostic pathway (e.g., starting with baseline labs/imaging before moving to invasive confirmatory tests) to arrive at the Target Diagnosis.
- Terminology: Use specific, professional medical terminology for all orders (e.g., "Comprehensive Metabolic Panel" or "CT Angiography of the Chest with IV contrast" instead of "blood test" or "scan").
- Relevance: Every ordered procedure must have a clear clinical indication tied directly to the patient's presentation in the outline.
- Return ONLY the JSON object, no additional text like prefix or suffix.`
  );

  const userPrompt = buildPrompt(
    `Target Diagnosis: ${diagnosis.name} ${diagnosis.icd ?? ""}`,

    `Case Outline: ${outline}`,

    userInstructions
      ? `Additional Instructions: ${userInstructions}`
      : undefined
  );

  console.debug(
    `[GenerateProceduresFromOutline] Prompt:\n${systemPrompt}\n${userPrompt}`
  );

  // Initialize cases to empty in case of failure
  try {
    const ProcedureSchemaWrapper = z.object({
      procedures: z
        .array(ProcedureGenerationSchema)
        .describe("Generated procedures"),
    });

    const procedures: ProcedureGeneration[] = await retry(
      async (attempt: number, previousError?: Error) => {
        const result = await getCreativeLLM()
          .withStructuredOutput(ProcedureSchemaWrapper)
          .invoke([
            new SystemMessage(systemPrompt),
            new HumanMessage(
              userPrompt +
                (previousError
                  ? `\nPrevious generation error: ${previousError.message}`
                  : "")
            ),
          ])
          .catch((error) => {
            handleLangchainError(error);
          });

        console.debug(
          `[GenerateProceduresFromOutline] [Attempt ${attempt}] LLM raw Response:\n`,
          JSON.stringify(result)
        );

        const filteredProcedures = result.procedures.filter((p) =>
          procedureList
            ? procedureList.some((inputP) =>
                inputP.name.toLowerCase().includes(p.name.toLowerCase())
              )
            : true
        );

        if (filteredProcedures.length === 0) {
          throw new Error(
            `No generated procedures could be mapped to provided procedure list. Generated procedures: ${result.procedures
              .map((p) => p.name)
              .join(", ")}`
          );
        }

        return filteredProcedures;
      },
      2,
      0,
      (error, attempt) => {
        emitTrace(
          `[GenerateProceduresFromOutline] Attempt ${attempt} failed with error: ${error.message}`,
          { category: "error" }
        );
      }
    );

    return procedures;
  } catch (error) {
    console.error(`[GenerateProceduresFromOutline] Error:`, error);
    throw error;
  }
}

export async function generateProceduresCoT(
  diagnosis: Diagnosis,
  symptoms: Symptom[],
  relatedCase?: Case,
  userInstructions?: string
): Promise<string> {
  const systemPrompt = buildPrompt(
    `You are a senior doctor whos patient has these symptoms: 
${symptoms.map((s) => s.name).join(", ")}
You want to help a junior doctor to decide which procedures to schedule to come to a diagnosis. For that you should generate a step by step reasoning process to let the junior determine which procedures should be performed.`,

    "Return the thinking steps as a list in markdown format. Do not return any additional text like prefix or suffix text, only the markdown list.",

    relatedCase
      ? `The patient case has the following properties which might be relevant for the procedures generation:
${JSON.stringify(relatedCase)}`
      : undefined
  );

  const userPrompt = [
    `Provided Diagnosis: ${diagnosis.name} ${diagnosis.icd ?? ""}`,
    userInstructions
      ? `Additional provided instructions: ${userInstructions}`
      : "",
  ]
    .filter((s) => s.length > 0)
    .join("\n");

  console.debug(
    `[GenerateProceduresCoT] Prompt:\n${systemPrompt}\n${userPrompt}`
  );

  try {
    const stepsString: string = await retry(
      async (attempt: number) => {
        const text = await getDeterministicLLM({ outputFormat: "text" })
          .invoke([
            new SystemMessage(systemPrompt),
            new HumanMessage(userPrompt),
          ])
          .catch((error) => {
            handleLangchainError(error);
          });
        console.debug(
          `[GenerateProceduresCoT] [Attempt ${attempt}] LLM raw Response:\n`,
          text
        );

        return text.text;
      },
      2,
      0,
      (error, attempt) => {
        emitTrace(
          `[GenerateProceduresCoT] Attempt ${attempt} failed with error: ${error.message}`,
          { category: "error" }
        );
      }
    );

    return stepsString;
  } catch (error) {
    console.error(`[GenerateProceduresCoT] Error:`, error);
    throw error;
  }
}

export async function generateProceduresOneShot(
  diagnosis: Diagnosis, // provided by the user
  symptoms: Symptom[], // generate by a chain step
  relatedCase?: Case, // generated by a previous chain step
  cot?: string, // generated by a previous chain step
  userInstructions?: string, // provided by the user
  procedureList: Procedure[] | undefined = PredefinedProcedures,
  inconsistencies?: Inconsistency[] // generated by a previous chain step
): Promise<ProcedureGeneration[]> {
  const { procedures: previousProcedures, ...caseWithoutProcedures } =
    relatedCase ?? {};

  const systemPrompt = buildPrompt(
    `You are a doctor whos patient has these symptoms: 
${symptoms.map((s) => s.name).join(", ")}`,

    procedureList?.length
      ? `Select procedures from the following list of procedures that should be performed on the patient to come to a diagnosis:
${procedureList.map((p) => `- ${p.name}`).join("\n")}`
      : `Generate procedures that should be performed for the patient to come to a diagnosis.`,

    cot ? `Think step by step:\n${cot}` : undefined,

    Object.keys(caseWithoutProcedures).length > 0
      ? `The patient case has the following properties which might be relevant for the procedures:
  ${JSON.stringify(caseWithoutProcedures)}`
      : undefined,

    previousProcedures
      ? `Try to fix the inconsistencies from the previous procedures:
${JSON.stringify({ procedures: previousProcedures })}
with inconsistencies:
${inconsistencies
  ?.map((i, idx) => {
    return `${idx + 1}. severity ${i.severity}: ${i.description}
suggested fix: ${i.suggestion}`;
  })
  .join("\n")}`
      : undefined,

    `Return your response in JSON
${`{ "procedures": ${ProcedureGenerationArrayJsonExampleString()} }`}`,

    `Requirements:
- Be medically accurate and realistic
- Use standard medical terminology
- The procedure "name" field MUST exactly match a name returned by the "query_procedures" tool
- Return ONLY the JSON object, no additional text like prefix or suffix text`
  );

  const userPrompt = buildPrompt(
    `Provided Diagnosis: ${diagnosis.name} ${diagnosis.icd ?? ""}`,
    userInstructions
      ? `Additional provided instructions: ${userInstructions}`
      : undefined
  );

  console.debug(
    `[GenerateProceduresOneShot] Prompt:\n${systemPrompt}\n${userPrompt}`
  );

  // Initialize cases to empty in case of failure
  try {
    const ProcedureSchemaWrapper = z.object({
      procedures: z
        .array(ProcedureGenerationSchema)
        .describe("Generated procedures"),
    });

    const procedures: ProcedureGeneration[] = await retry(
      async (attempt: number) => {
        const result = await getCreativeLLM()
          .withStructuredOutput(ProcedureSchemaWrapper)
          .invoke([
            new SystemMessage(systemPrompt),
            new HumanMessage(userPrompt),
          ])
          .catch((error) => {
            handleLangchainError(error);
          });

        console.debug(
          `[GenerateProceduresOneShot] [Attempt ${attempt}] LLM raw Response:\n`,
          JSON.stringify(result)
        );

        const filteredProcedures = result.procedures.filter((p) =>
          procedureList
            ? procedureList.some((inputP) =>
                inputP.name.toLowerCase().includes(p.name.toLowerCase())
              )
            : true
        );

        if (filteredProcedures.length === 0) {
          throw new Error(
            `No generated procedures could be mapped to provided procedure list. Generated procedures: ${result.procedures
              .map((p) => p.name)
              .join(", ")}`
          );
        }

        return filteredProcedures;
      },
      2,
      0,
      (error, attempt) => {
        emitTrace(
          `[GenerateProceduresOneShot] Attempt ${attempt} failed with error: ${error.message}`,
          { category: "error" }
        );
      }
    );

    return procedures;
  } catch (error) {
    console.error(`[GenerateProceduresOneShot] Error:`, error);
    throw error;
  }
}

export async function generateProceduresFromEnglish(
  procedures: Procedure[],
  language: Language
): Promise<(Procedure | undefined)[]> {
  const systemPrompt = `Translate the provided procedures from English to a target language:
  
Return the procedures mapped to their translated part in a JSON
{
  "provided procedure1": "translated procedure1",
  "provided procedure2": "translated procedure2",
  ...
}
ONLY return the JSON object, no additional text.`;

  const userPrompt = `Target language: ${language}
Procedures to translate:
${procedures.map((p) => p.name.toLowerCase()).join("\n")}`;

  console.debug(
    `[Procedures Service] Generating procedure translations with prompt: 
  ${systemPrompt}
  ${userPrompt}`
  );

  const prompt = [
    { role: "system", content: systemPrompt },
    { role: "user", content: userPrompt },
  ];

  const parsed = await retry(
    async () => {
      const response = await getDeterministicLLM().invoke(prompt);

      console.debug(
        "[Procedures Service] Generated procedure translations:",
        response.text
      );

      const responseSchema = z.record(z.string(), z.string());
      return responseSchema.parse(JSON.parse(response.text));
    },
    2,
    0
  );

  // Filter only the requested procedures
  const sortedTranslation: (Procedure | undefined)[] = procedures.map(
    () => undefined
  );
  for (const [original, translated] of Object.entries(parsed)) {
    const index = procedures
      .map((p) => p.name.toLowerCase())
      .indexOf(original.toLowerCase());
    if (index === -1) {
      continue; // keep the original procedure if no translation was provided
      // throw new Error(
      //   `The procedure "${original}" was not in the list of procedures to translate.`
      // );
    }
    sortedTranslation[index] = { name: translated };
  }

  return sortedTranslation;
}
