import {
  getCreativeLLM,
  getDeterministicLLM,
  handleLangchainError,
  parseStructuredResponse,
} from "@/ai/llm.js";
import type { Inconsistency } from "@/domain-models/Inconsistency.js";
import type { Diagnosis } from "@/domain-models/Diagnosis.js";
import type { Symptom } from "@/domain-models/Symptom.js";
import {
  createAgent,
  HumanMessage,
  providerStrategy,
  SystemMessage,
} from "langchain";
import { retry } from "@/utils/retry.js";
import {
  ChiefComplaintJsonExample,
  ChiefComplaintJsonSchema,
  type ChiefComplaint,
} from "@/domain-models/ChiefComplaint.js";

export async function generateChiefComplaintCoT(
  diagnosis: Diagnosis,
  symptoms: Symptom[],
  userInstructions?: string
): Promise<string> {
  const systemPrompt = `You are a Doctor who intakes a patient with these symptoms: 
${symptoms.map((s) => s.name).join(", ")}
Your task is to generate a step by step reasoning process, which should help the next doctor to fill in the chief complaint.

The next doctor will receive the list of symptoms and output the chief complaint in the following format:
${JSON.stringify(ChiefComplaintJsonExample())}

Generate the chain of thought as a list of steps.
ONLY return the list of steps, do not return the chief complaint or any additional text.`;

  const userPrompt = [
    `Provided Diagnosis: ${diagnosis.name} ${diagnosis.icd ?? ""}`,
    userInstructions
      ? `Additional provided instructions: ${userInstructions}`
      : "",
  ]
    .filter((s) => s.length > 0)
    .join("\n");

  console.debug(
    `[GenerateChiefComplaintCoT] Prompt:\n${systemPrompt}\n${userPrompt}`
  );

  try {
    const stepsString: string = await retry(
      async () => {
        const text = await getDeterministicLLM({ outputFormat: "text" })
          .invoke([
            new SystemMessage(systemPrompt),
            new HumanMessage(userPrompt),
          ])
          .catch((error) => {
            handleLangchainError(error);
          });
        console.debug("[GenerateChiefComplaintCoT] LLM raw Response:\n", text);

        return text.text;
      },
      2,
      0
    );

    return stepsString;
  } catch (error) {
    console.error(`[GenerateChiefComplaintCoT] Error:`, error);
    throw error;
  }
}

export async function generateChiefComplaintOneShot(
  diagnosis: Diagnosis, // provided by the user
  symptoms: Symptom[], // generate by a chain step
  cot?: string, // generated by a previous chain step
  userInstructions?: string, // provided by the user
  previousChiefComplaint?: ChiefComplaint, // generated by a previous chain step
  inconsistencies?: Inconsistency[] // generated by a previous chain step
): Promise<ChiefComplaint> {
  const systemPrompt = `You are a doctor with a patient with these symptoms: 
${symptoms.map((s) => s.name).join(", ")}
Generate a chief complaint in your words with medical terminology.
${cot ? `Think step by step:\n${cot}` : ""}
${
  previousChiefComplaint
    ? `Try to fix the inconsistencies from the previous chief complaint generated:\n${JSON.stringify(previousChiefComplaint)}
with inconsistencies:
${inconsistencies
  ?.map((i, idx) => {
    return `${idx + 1}. severity ${i.severity}: ${i.description}
suggested fix: ${i.suggestion}`;
  })
  .join("\n")}`
    : ``
}
Return your response in JSON:
${JSON.stringify(ChiefComplaintJsonExample())}

Requirements:
- Be medically accurate and realistic
- Use standard medical terminology
- Return ONLY the JSON content, no additional text`;

  const userPrompt = [
    `Provided Diagnosis: ${diagnosis.name} ${diagnosis.icd ?? ""}`,
    userInstructions
      ? `Additional provided instructions: ${userInstructions}`
      : "",
  ]
    .filter((s) => s.length > 0)
    .join("\n");

  console.debug(
    `[GenerateChiefComplaintOneShot] Prompt:\n${systemPrompt}\n${userPrompt}`
  );

  // Initialize cases to empty in case of failure
  try {
    const chiefComplaint: ChiefComplaint = await retry(
      async () => {
        const result = await createAgent({
          model: getCreativeLLM(),
          tools: [],
          systemPrompt: systemPrompt,
          responseFormat: providerStrategy(ChiefComplaintJsonSchema),
        })
          .invoke({ messages: [new HumanMessage(userPrompt)] })
          .catch((error) => {
            handleLangchainError(error);
          });
        console.debug(
          "[GenerateChiefComplaintOneShot] LLM raw Response:\ncontent:\n",
          result.messages[result.messages.length - 1]?.content,
          "\nstructured response:\n",
          result.structuredResponse
        );

        return parseStructuredResponse(result, ChiefComplaintJsonSchema)
          .chiefComplaint;
      },
      2,
      0
    );

    return chiefComplaint;
  } catch (error) {
    console.error(`[GenerateChiefComplaintOneShot] Error:`, error);
    throw error;
  }
}
