import {
  getCreativeLLM,
  getDeterministicLLM,
  handleLangchainError,
  parseStructuredResponseAgent,
} from "@/ai/llm.js";
import type { Case } from "@/domain-models/Case.js";
import type { Diagnosis } from "@/domain-models/Diagnosis.js";
import type { Inconsistency } from "@/domain-models/Inconsistency.js";
import {
  ProcedureArrayJsonExampleString,
  ProcedureSchema,
  type Procedure,
} from "@/domain-models/Procedure.js";
import type { Symptom } from "@/domain-models/Symptom.js";
import { retry } from "@/utils/retry.js";
import {
  createAgent,
  HumanMessage,
  providerStrategy,
  SystemMessage,
} from "langchain";
import z from "zod";

export async function generateProceduresCoT(
  diagnosis: Diagnosis,
  symptoms: Symptom[],
  relatedCase?: Case,
  userInstructions?: string
): Promise<string> {
  const systemPrompt = `You are a doctor whos patient has these symptoms: 
${symptoms.map((s) => s.name).join(", ")}
Generate a step by step reasoning process which procedures should be performed.
Return the steps as a list of steps in markdown format.
${
  relatedCase
    ? `The patient case has the following properties which might be relevant for the procedures generation:
  ${JSON.stringify(relatedCase)}`
    : ""
}`;

  const userPrompt = [
    `Provided Diagnosis: ${diagnosis.name} ${diagnosis.icd ?? ""}`,
    userInstructions
      ? `Additional provided instructions: ${userInstructions}`
      : "",
  ]
    .filter((s) => s.length > 0)
    .join("\n");

  console.debug(
    `[GenerateProceduresCoT] Prompt:\n${systemPrompt}\n${userPrompt}`
  );

  try {
    const stepsString: string = await retry(
      async () => {
        const text = await getDeterministicLLM({ outputFormat: "text" })
          .invoke([
            new SystemMessage(systemPrompt),
            new HumanMessage(userPrompt),
          ])
          .catch((error) => {
            handleLangchainError(error);
          });
        console.debug("[GenerateProceduresCoT] LLM raw Response:\n", text);

        return text.text;
      },
      2,
      0
    );

    return stepsString;
  } catch (error) {
    console.error(`[GenerateProceduresCoT] Error:`, error);
    throw error;
  }
}

export async function generateProceduresOneShot(
  diagnosis: Diagnosis, // provided by the user
  symptoms: Symptom[], // generate by a chain step
  relatedCase?: Case, // generated by a previous chain step
  cot?: string, // generated by a previous chain step
  userInstructions?: string, // provided by the user
  inconsistencies?: Inconsistency[] // generated by a previous chain step
): Promise<Procedure[]> {
    const { procedures: previousProcedures, ...caseWithoutProcedures } = relatedCase ?? {};

  const systemPrompt = `You are a doctor whos patient has these symptoms: 
${symptoms.map((s) => s.name).join(", ")}
Generate a list of procedures that should be performed.
${cot ? `Think step by step:\n${cot}` : ""}
${
  Object.keys(caseWithoutProcedures).length > 0
    ? `The patient case has the following properties which might be relevant for the procedures generation:
  ${JSON.stringify(caseWithoutProcedures)}`
    : ""
}
${
    previousProcedures
    ? `Try to fix the inconsistencies from the previous procedures generated:\n${JSON.stringify({ procedures: previousProcedures })}
with inconsistencies:
${inconsistencies
  ?.map((i, idx) => {
    return `${idx + 1}. severity ${i.severity}: ${i.description}
suggested fix: ${i.suggestion}`;
  })
  .join("\n")}`
    : ``
}
Return your response in JSON
${`({ "procedures": ${ProcedureArrayJsonExampleString()} })`}

Requirements:
- Be medically accurate and realistic
- Use standard medical terminology
- Return ONLY the JSON object, no additional text`;

  const userPrompt = [
    `Provided Diagnosis: ${diagnosis.name} ${diagnosis.icd ?? ""}`,
    userInstructions
      ? `Additional provided instructions: ${userInstructions}`
      : "",
  ]
    .filter((s) => s.length > 0)
    .join("\n");

  console.debug(
    `[GenerateProceduresOneShot] Prompt:\n${systemPrompt}\n${userPrompt}`
  );

  // Initialize cases to empty in case of failure
  try {
    const ProcedureSchemaWrapper = z.object({
      procedures: z.array(ProcedureSchema).describe("Generated procedures"),
    });

    const procedures: Procedure[] = await retry(
      async () => {
        const result = await createAgent({
          model: getCreativeLLM(),
          tools: [],
          systemPrompt: systemPrompt,
          responseFormat: providerStrategy(ProcedureSchemaWrapper),
        })
          .invoke({ messages: [new HumanMessage(userPrompt)] })
          .catch((error) => {
            handleLangchainError(error);
          });

        console.debug(
          "[GenerateProceduresOneShot] LLM raw Response:\ncontent:\n",
          result.messages[result.messages.length - 1]?.content,
          "\nstructured response:\n",
          result.structuredResponse
        );

        return parseStructuredResponseAgent(result, ProcedureSchemaWrapper)
          .procedures;
      },
      2,
      0
    );

    return procedures;
  } catch (error) {
    console.error(`[GenerateProceduresOneShot] Error:`, error);
    throw error;
  }
}
