import type { GraphRuntime } from "@/core/graph/runtime.js";
import type {
  SymptomCache,
  UmlsSymptomFloor,
} from "@/core/graph/02-plan/01-basis/ports.js";
import { generateSymptomsOneShot } from "./llmSymptoms.gateway.js";
import type { MedicalBasisProvider } from "@/core/graph/02-plan/01-basis/ports.js";

const ID = "llm-symptoms";

/**
 * Fallback for `umls-symptoms`: nothing when UMLS has data for the ICD code;
 * otherwise LLM-generated symptoms, cache-aside per ICD code (fresh hit skips
 * the LLM; no ICD code or empty result = never cached).
 */
export function createLlmSymptomProvider(
  runtime: GraphRuntime,
  umlsFloor: UmlsSymptomFloor,
  symptomCache: SymptomCache
): MedicalBasisProvider {
  return {
    id: ID,
    description: "Typical symptoms (generated by a language model)",
    async fetch(query, context) {
      const icd = query.diagnosis.icd;
      if (icd && umlsFloor.SymptomsRelatedToDiagnosisIcd(icd).length > 0) {
        return undefined;
      }

      let symptoms = icd ? symptomCache.getCachedSymptoms(icd) : undefined;
      if (symptoms) {
        runtime.log.info(`[MedicalBasis:${ID}] cache hit for ICD ${icd}`);
      } else {
        symptoms = await generateSymptomsOneShot(
          runtime,
          query.diagnosis,
          query.userInstructions,
          context
        );
        runtime.log.info(
          `[MedicalBasis:${ID}] cache miss${icd ? ` for ICD ${icd}` : ""}, generated: ${symptoms.map((s) => s.name).join(", ")}`
        );
        if (icd && symptoms.length > 0) {
          symptomCache.saveCachedSymptoms(icd, symptoms);
        }
      }

      return symptoms.map((s) => s.name).join(", ") || undefined;
    },
  };
}
