import {
  buildPrompt,
  getCreativeLLM,
  getDeterministicLLM,
  handleLangchainError,
  parseStructuredResponseAgent,
} from "@/utils/llm.js";
import type { Case } from "@/02domain-models/Case.js";
import type { Diagnosis } from "@/02domain-models/Diagnosis.js";
import type { Inconsistency } from "@/02domain-models/Inconsistency.js";
import {
  PredefinedProcedures,
  ProcedureWithRelevanceArrayJsonExampleString,
  ProcedureWithRelevanceSchema,
  type ProcedureWithRelevance,
} from "@/02domain-models/Procedure.js";
import type { Symptom } from "@/02domain-models/Symptom.js";
import { retry } from "@/utils/retry.js";
import {
  createAgent,
  HumanMessage,
  providerStrategy,
  SystemMessage,
} from "langchain";
import z from "zod";

export async function generateProceduresCoT(
  diagnosis: Diagnosis,
  symptoms: Symptom[],
  relatedCase?: Case,
  userInstructions?: string
): Promise<string> {
  const systemPrompt = buildPrompt(
    `You are a senior doctor whos patient has these symptoms: 
${symptoms.map((s) => s.name).join(", ")}
You want to help a junior doctor to decide which procedures to schedule. For that you should generate a step by step reasoning process to let the junior determine which procedures should be performed.`,
    "Return the thinking steps as a list in markdown format. Do not return any additional text like prefix or suffix text, only the markdown list.",

    relatedCase
      ? `The patient case has the following properties which might be relevant for the procedures generation:
${JSON.stringify(relatedCase)}`
      : undefined
  );

  const userPrompt = [
    `Provided Diagnosis: ${diagnosis.name} ${diagnosis.icd ?? ""}`,
    userInstructions
      ? `Additional provided instructions: ${userInstructions}`
      : "",
  ]
    .filter((s) => s.length > 0)
    .join("\n");

  console.debug(
    `[GenerateProceduresCoT] Prompt:\n${systemPrompt}\n${userPrompt}`
  );

  try {
    const stepsString: string = await retry(
      async () => {
        const text = await getDeterministicLLM({ outputFormat: "text" })
          .invoke([
            new SystemMessage(systemPrompt),
            new HumanMessage(userPrompt),
          ])
          .catch((error) => {
            handleLangchainError(error);
          });
        console.debug("[GenerateProceduresCoT] LLM raw Response:\n", text);

        return text.text;
      },
      2,
      0
    );

    return stepsString;
  } catch (error) {
    console.error(`[GenerateProceduresCoT] Error:`, error);
    throw error;
  }
}

export async function generateProceduresOneShot(
  diagnosis: Diagnosis, // provided by the user
  symptoms: Symptom[], // generate by a chain step
  relatedCase?: Case, // generated by a previous chain step
  cot?: string, // generated by a previous chain step
  userInstructions?: string, // provided by the user
  inconsistencies?: Inconsistency[] // generated by a previous chain step
): Promise<ProcedureWithRelevance[]> {
  const { procedures: previousProcedures, ...caseWithoutProcedures } =
    relatedCase ?? {};

  const systemPrompt = buildPrompt(
    `You are a doctor whos patient has these symptoms: 
${symptoms.map((s) => s.name).join(", ")}`,
    `Generate procedures that should be performed for the patient.`,

    PredefinedProcedures?.length
      ? `Pick only procedures from the following list of procedures:\n${PredefinedProcedures.map((p) => `- ${p.name}`).join("\n")}`
      : undefined,

    cot ? `Think step by step:\n${cot}` : undefined,

    Object.keys(caseWithoutProcedures).length > 0
      ? `The patient case has the following properties which might be relevant for the procedures generation:
  ${JSON.stringify(caseWithoutProcedures)}`
      : undefined,

    previousProcedures
      ? `Try to fix the inconsistencies from the previous procedures generated:\n${JSON.stringify({ procedures: previousProcedures })}
with inconsistencies:
${inconsistencies
  ?.map((i, idx) => {
    return `${idx + 1}. severity ${i.severity}: ${i.description}
suggested fix: ${i.suggestion}`;
  })
  .join("\n")}`
      : undefined,

    `Return your response in JSON
${`{ "procedures": ${ProcedureWithRelevanceArrayJsonExampleString()} }`}`,

    `Requirements:
- Be medically accurate and realistic
- Use standard medical terminology
- The procedure "name" field MUST exactly match a name returned by the "query_procedures" tool
- Return ONLY the JSON object, no additional text like prefix or suffix text`
  );

  const userPrompt = buildPrompt(
    `Provided Diagnosis: ${diagnosis.name} ${diagnosis.icd ?? ""}`,
    userInstructions
      ? `Additional provided instructions: ${userInstructions}`
      : undefined
  );

  console.debug(
    `[GenerateProceduresOneShot] Prompt:\n${systemPrompt}\n${userPrompt}`
  );

  // Initialize cases to empty in case of failure
  try {
    const ProcedureSchemaWrapper = z.object({
      procedures: z
        .array(ProcedureWithRelevanceSchema)
        .describe("Generated procedures"),
    });

    const procedures: ProcedureWithRelevance[] = await retry(
      async () => {
        const result = await createAgent({
          model: getCreativeLLM(),
          systemPrompt: systemPrompt,
          responseFormat: providerStrategy(ProcedureSchemaWrapper),
        })
          .invoke({ messages: [new HumanMessage(userPrompt)] })
          .catch((error) => {
            handleLangchainError(error);
          });

        console.debug(
          "[GenerateProceduresOneShot] LLM raw Response:\ncontent:\n",
          result.messages[result.messages.length - 1]?.content,
          "\nstructured response:\n",
          result.structuredResponse
        );

        return parseStructuredResponseAgent(result, ProcedureSchemaWrapper)
          .procedures;
      },
      2,
      0
    );

    return procedures;
  } catch (error) {
    console.error(`[GenerateProceduresOneShot] Error:`, error);
    throw error;
  }
}
