import type { GraphRuntime } from "@/core/graph/runtime.js";
import type { SymptomsRepo } from "@/core/graph/symptoms/repo.js";
import { generateSymptomsOneShot } from "@/core/graph/03aigateway/symptoms.aigateway.js";
import type { MedicalBasisProvider } from "../ports.js";

const ID = "llm-symptoms";

/**
 * Fallback for `umls-symptoms`: nothing when UMLS has data for the ICD code;
 * otherwise LLM-generated symptoms, cache-aside per ICD code (fresh hit skips
 * the LLM; no ICD code or empty result = never cached).
 */
export function createLlmSymptomProvider(
  runtime: GraphRuntime,
  symptomsRepo: SymptomsRepo
): MedicalBasisProvider {
  return {
    id: ID,
    description: "Typical symptoms (generated by a language model)",
    async fetch(query, context) {
      const icd = query.diagnosis.icd;
      if (icd && symptomsRepo.SymptomsRelatedToDiagnosisIcd(icd).length > 0) {
        return undefined;
      }

      let symptoms = icd ? symptomsRepo.getCachedSymptoms(icd) : undefined;
      if (symptoms) {
        runtime.log.info(`[MedicalBasis:${ID}] cache hit for ICD ${icd}`);
      } else {
        symptoms = await generateSymptomsOneShot(
          runtime,
          query.diagnosis,
          query.userInstructions,
          context
        );
        runtime.log.info(
          `[MedicalBasis:${ID}] cache miss${icd ? ` for ICD ${icd}` : ""}, generated: ${symptoms.map((s) => s.name).join(", ")}`
        );
        if (icd && symptoms.length > 0) {
          symptomsRepo.saveCachedSymptoms(icd, symptoms);
        }
      }

      return symptoms.map((s) => s.name).join(", ") || undefined;
    },
  };
}
