%%{init: {'flowchart': {'curve': 'linear'}}}%%
graph TD;
	__start__([<p>__start__</p>]):::first
	translation_to_english_phase___start__(<p>__start__</p>)
	translation_to_english_phase_translate_diagnosis(translate_diagnosis)
	translation_to_english_phase_translate_user_instructions(translate_user_instructions)
	translation_to_english_phase___end__(<p>__end__</p>)
	planning_phase_basis_resolve(basis_resolve)
	planning_phase_outline_phase_case_outline_generate(case_outline_generate)
	planning_phase_outline_phase_outline_evaluate(outline_evaluate)
	planning_phase_outline_phase_outline_regenerate(outline_regenerate)
	planning_phase_outline_phase___end__(<p>__end__</p>)
	__end__([<p>__end__</p>]):::last
	planning_phase_outline_phase___end__ --> __end__;
	translation_to_english_phase___end__ --> planning_phase_basis_resolve;
	__start__ -. &nbsp;translate&nbsp; .-> translation_to_english_phase___start__;
	__start__ -. &nbsp;skip&nbsp; .-> planning_phase_basis_resolve;
	subgraph translation_to_english_phase
	translation_to_english_phase___start__ --> translation_to_english_phase_translate_diagnosis;
	translation_to_english_phase___start__ --> translation_to_english_phase_translate_user_instructions;
	translation_to_english_phase_translate_diagnosis --> translation_to_english_phase___end__;
	translation_to_english_phase_translate_user_instructions --> translation_to_english_phase___end__;
	end
	subgraph planning_phase
	subgraph outline_phase
	planning_phase_outline_phase_case_outline_generate --> planning_phase_outline_phase_outline_evaluate;
	planning_phase_outline_phase_outline_evaluate -.-> planning_phase_outline_phase_outline_regenerate;
	planning_phase_outline_phase_outline_evaluate -.-> planning_phase_outline_phase___end__;
	planning_phase_outline_phase_outline_regenerate -.-> planning_phase_outline_phase_outline_evaluate;
	end
	planning_phase_basis_resolve --> planning_phase_outline_phase_case_outline_generate;
	end
	classDef default fill:#f2f0ff,line-height:1.2;
	classDef first fill-opacity:0;
	classDef last fill:#bfb6fc;
