%%{init: {'flowchart': {'curve': 'linear'}}}%%
graph TD;
	__start__([<p>__start__</p>]):::first
	planning_phase_basis_resolve(basis_resolve)
	planning_phase_outline_phase_case_outline_generate(case_outline_generate)
	planning_phase_outline_phase_outline_evaluate(outline_evaluate)
	planning_phase_outline_phase_outline_regenerate(outline_regenerate)
	planning_phase_outline_phase___end__(<p>__end__</p>)
	human_review(human_review)
	generation_phase_presentation_phase___start__(<p>__start__</p>)
	generation_phase_presentation_phase_patient_generate(patient_generate)
	generation_phase_presentation_phase_chief_complaint_generate_plan_content(plan_content)
	generation_phase_presentation_phase_chief_complaint_generate_render_parts(render_parts)
	generation_phase_presentation_phase_anamnesis_generate_plan_content(plan_content)
	generation_phase_presentation_phase_anamnesis_generate_render_parts(render_parts)
	generation_phase_presentation_phase_case_fan_in(case_fan_in)
	generation_phase_procedure_phase___start__(<p>__start__</p>)
	generation_phase_procedure_phase_blinded_step(blinded_step)
	generation_phase_procedure_phase_result_step(result_step)
	generation_phase_procedure_phase_bridge(bridge)
	generation_phase_procedure_phase_render_results(render_results)
	__end__([<p>__end__</p>]):::last
	__start__ --> planning_phase_basis_resolve;
	generation_phase_procedure_phase_render_results --> __end__;
	human_review --> generation_phase_presentation_phase___start__;
	planning_phase_outline_phase___end__ --> human_review;
	subgraph planning_phase
	subgraph outline_phase
	planning_phase_outline_phase_case_outline_generate --> planning_phase_outline_phase_outline_evaluate;
	planning_phase_outline_phase_outline_evaluate -.-> planning_phase_outline_phase_outline_regenerate;
	planning_phase_outline_phase_outline_evaluate -.-> planning_phase_outline_phase___end__;
	planning_phase_outline_phase_outline_regenerate -.-> planning_phase_outline_phase_outline_evaluate;
	end
	planning_phase_basis_resolve --> planning_phase_outline_phase_case_outline_generate;
	end
	subgraph generation_phase
	subgraph presentation_phase
	subgraph chief_complaint_generate
	generation_phase_presentation_phase_chief_complaint_generate_plan_content --> generation_phase_presentation_phase_chief_complaint_generate_render_parts;
	end
	subgraph anamnesis_generate
	generation_phase_presentation_phase_anamnesis_generate_plan_content --> generation_phase_presentation_phase_anamnesis_generate_render_parts;
	end
	generation_phase_presentation_phase_anamnesis_generate_render_parts --> generation_phase_presentation_phase_case_fan_in;
	generation_phase_presentation_phase_chief_complaint_generate_render_parts --> generation_phase_presentation_phase_case_fan_in;
	generation_phase_presentation_phase_patient_generate --> generation_phase_presentation_phase_case_fan_in;
	generation_phase_presentation_phase___start__ -.-> generation_phase_presentation_phase_patient_generate;
	generation_phase_presentation_phase___start__ -.-> generation_phase_presentation_phase_chief_complaint_generate_plan_content;
	generation_phase_presentation_phase___start__ -.-> generation_phase_presentation_phase_anamnesis_generate_plan_content;
	end
	subgraph procedure_phase
	generation_phase_procedure_phase___start__ --> generation_phase_procedure_phase_blinded_step;
	generation_phase_procedure_phase_blinded_step -.-> generation_phase_procedure_phase_result_step;
	generation_phase_procedure_phase_blinded_step -.-> generation_phase_procedure_phase_bridge;
	generation_phase_procedure_phase_blinded_step -.-> generation_phase_procedure_phase_render_results;
	generation_phase_procedure_phase_result_step -.-> generation_phase_procedure_phase_blinded_step;
	generation_phase_procedure_phase_bridge -.-> generation_phase_procedure_phase_render_results;
	end
	generation_phase_presentation_phase_case_fan_in -. &nbsp;generate&nbsp; .-> generation_phase_procedure_phase___start__;
	end
	classDef default fill:#f2f0ff,line-height:1.2;
	classDef first fill-opacity:0;
	classDef last fill:#bfb6fc;
