%%{init: {'flowchart': {'curve': 'linear'}}}%%
graph TD;
	__start__([<p>__start__</p>]):::first
	translate_in_phase___start__(<p>__start__</p>)
	translate_in_phase_translate_diagnosis(translate_diagnosis)
	translate_in_phase_translate_user_instructions(translate_user_instructions)
	translate_in_phase___end__(<p>__end__</p>)
	plan_phase_basis_resolve(basis_resolve)
	plan_phase_outline_phase_case_outline_generate(case_outline_generate)
	plan_phase_outline_phase_outline_evaluate(outline_evaluate)
	plan_phase_outline_phase_outline_regenerate(outline_regenerate)
	plan_phase_outline_phase___end__(<p>__end__</p>)
	outline_translation_out(outline_translation_out)
	human_review(human_review)
	outline_translation_in(outline_translation_in)
	case_phase_presentation_phase___start__(<p>__start__</p>)
	case_phase_presentation_phase_patient_generate(patient_generate)
	case_phase_presentation_phase_chief_complaint_phase_plan_content(plan_content)
	case_phase_presentation_phase_chief_complaint_phase_render_parts(render_parts)
	case_phase_presentation_phase_anamnesis_phase_plan_content(plan_content)
	case_phase_presentation_phase_anamnesis_phase_render_parts(render_parts)
	case_phase_presentation_phase_case_fan_in(case_fan_in)
	case_phase_procedures_phase___start__(<p>__start__</p>)
	case_phase_procedures_phase_blinded_step(blinded_step)
	case_phase_procedures_phase_result_step(result_step)
	case_phase_procedures_phase_bridge(bridge)
	case_phase_procedures_phase_render_results(render_results)
	translate_out_phase___start__(<p>__start__</p>)
	translate_out_phase_translate_defined(translate_defined)
	translate_out_phase_translate_rest(translate_rest)
	translate_out_phase_translate_merge(translate_merge)
	__end__([<p>__end__</p>]):::last
	translate_in_phase___end__ -.-> plan_phase_basis_resolve;
	case_phase_procedures_phase_render_results -. &nbsp;translate&nbsp; .-> translate_out_phase___start__;
	__start__ --> translate_in_phase___start__;
	translate_out_phase_translate_merge --> __end__;
	human_review --> outline_translation_in;
	outline_translation_in --> case_phase_presentation_phase___start__;
	outline_translation_out --> human_review;
	plan_phase_outline_phase___end__ --> outline_translation_out;
	subgraph translate_in_phase
	translate_in_phase___start__ --> translate_in_phase_translate_diagnosis;
	translate_in_phase___start__ --> translate_in_phase_translate_user_instructions;
	translate_in_phase_translate_diagnosis --> translate_in_phase___end__;
	translate_in_phase_translate_user_instructions --> translate_in_phase___end__;
	end
	subgraph plan_phase
	subgraph outline_phase
	plan_phase_outline_phase_case_outline_generate --> plan_phase_outline_phase_outline_evaluate;
	plan_phase_outline_phase_outline_evaluate -.-> plan_phase_outline_phase_outline_regenerate;
	plan_phase_outline_phase_outline_evaluate -.-> plan_phase_outline_phase___end__;
	plan_phase_outline_phase_outline_regenerate -.-> plan_phase_outline_phase_outline_evaluate;
	end
	plan_phase_basis_resolve --> plan_phase_outline_phase_case_outline_generate;
	end
	subgraph case_phase
	subgraph presentation_phase
	subgraph chief_complaint_phase
	case_phase_presentation_phase_chief_complaint_phase_plan_content --> case_phase_presentation_phase_chief_complaint_phase_render_parts;
	end
	subgraph anamnesis_phase
	case_phase_presentation_phase_anamnesis_phase_plan_content --> case_phase_presentation_phase_anamnesis_phase_render_parts;
	end
	case_phase_presentation_phase_anamnesis_phase_render_parts --> case_phase_presentation_phase_case_fan_in;
	case_phase_presentation_phase_chief_complaint_phase_render_parts --> case_phase_presentation_phase_case_fan_in;
	case_phase_presentation_phase_patient_generate --> case_phase_presentation_phase_case_fan_in;
	case_phase_presentation_phase___start__ -.-> case_phase_presentation_phase_patient_generate;
	case_phase_presentation_phase___start__ -.-> case_phase_presentation_phase_chief_complaint_phase_plan_content;
	case_phase_presentation_phase___start__ -.-> case_phase_presentation_phase_anamnesis_phase_plan_content;
	end
	subgraph procedures_phase
	case_phase_procedures_phase___start__ --> case_phase_procedures_phase_blinded_step;
	case_phase_procedures_phase_blinded_step -.-> case_phase_procedures_phase_result_step;
	case_phase_procedures_phase_blinded_step -.-> case_phase_procedures_phase_bridge;
	case_phase_procedures_phase_blinded_step -.-> case_phase_procedures_phase_render_results;
	case_phase_procedures_phase_result_step -.-> case_phase_procedures_phase_blinded_step;
	case_phase_procedures_phase_bridge -.-> case_phase_procedures_phase_render_results;
	end
	case_phase_presentation_phase_case_fan_in -. &nbsp;generate&nbsp; .-> case_phase_procedures_phase___start__;
	end
	subgraph translate_out_phase
	translate_out_phase___start__ --> translate_out_phase_translate_defined;
	translate_out_phase___start__ --> translate_out_phase_translate_rest;
	translate_out_phase_translate_defined --> translate_out_phase_translate_merge;
	translate_out_phase_translate_rest --> translate_out_phase_translate_merge;
	end
	classDef default fill:#f2f0ff,line-height:1.2;
	classDef first fill-opacity:0;
	classDef last fill:#bfb6fc;
