// AUTO-GENERATED by scripts/generate-registry.ts — do not edit manually

import { extension as _ext0 } from "./api/index.js";
import { extension as _ext1 } from "./debugLogger/index.js";
import { extension as _ext2 } from "./nats/index.js";
import { extension as _ext3 } from "./persistency/index.js";
import { extension as _ext4 } from "./rest/index.js";
import { extension as _ext5 } from "./swagger/index.js";
import { extension as _ext6 } from "./tracing/index.js";
import { extension as _ext7 } from "./tracingNats/index.js";
import { extension as _ext8 } from "./tracingPersistency/index.js";
import { extension as _ext9 } from "./tracingRest/index.js";

export const allExtensions = [
  _ext0,
  _ext1,
  _ext2,
  _ext3,
  _ext4,
  _ext5,
  _ext6,
  _ext7,
  _ext8,
  _ext9,
] as const;
