// AUTO-GENERATED by scripts/generate-registry.ts — do not edit manually

import { extension as _ext0 } from './core/index.js'
import { extension as _ext1 } from './debugLogger/index.js'
import { extension as _ext2 } from './nats/index.js'
import { extension as _ext3 } from './persistency/index.js'
import { extension as _ext4 } from './swagger/index.js'
import { extension as _ext5 } from './tracing/index.js'
import { extension as _ext6 } from './tracingPersistency/index.js'

export const allExtensions = [_ext0, _ext1, _ext2, _ext3, _ext4, _ext5, _ext6] as const
