import { readdirSync, writeFileSync, existsSync } from "fs";
import { join, resolve, dirname } from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const EXTENSIONS_DIR = resolve(__dirname, "../src/extensions");
const REGISTRY_PATH = join(EXTENSIONS_DIR, "_registry.ts");

// Ensure directory exists
if (!existsSync(EXTENSIONS_DIR)) {
  console.log(
    `[registry] Directory ${EXTENSIONS_DIR} does not exist. Created empty registry.`
  );
  writeFileSync(REGISTRY_PATH, "export const allExtensions = [] as const;\n");
  process.exit(0);
}

const names = readdirSync(EXTENSIONS_DIR, { withFileTypes: true })
  .filter((d) => d.isDirectory() && !d.name.startsWith("_"))
  .filter((d) => existsSync(join(EXTENSIONS_DIR, d.name, "index.ts")))
  .map((d) => d.name)
  // Ensure 'core' is loaded first for safety if needed, though top-sort handles this.
  .sort((a, b) => (a === "core" ? -1 : b === "core" ? 1 : a.localeCompare(b)));

const lines = [
  "// AUTO-GENERATED by scripts/generate-registry.ts — do not edit manually",
  "",
  ...names.map(
    (name, i) => `import { extension as _ext${i} } from './${name}/index.js'`
  ),
  "",
  `export const allExtensions = [${names.map((_, i) => `_ext${i}`).join(", ")}] as const`,
  "",
];

writeFileSync(REGISTRY_PATH, lines.join("\n"));
console.log(`[registry] Bundled extensions: [${names.join(", ") || "none"}]`);
