%%{init: {'flowchart': {'curve': 'linear'}}}%%
graph TD;
	__start__([<p>__start__</p>]):::first
	symptom_phase_symptoms_umls(symptoms_umls)
	symptom_phase_symptoms_generate(symptoms_generate)
	single_field_phase_instructions_reduce(instructions_reduce)
	single_field_phase_patient_cot(patient_cot)
	single_field_phase_patient_generate(patient_generate)
	single_field_phase_chiefComplaint_cot(chiefComplaint_cot)
	single_field_phase_chiefComplaint_generate(chiefComplaint_generate)
	single_field_phase_anamnesis_cot(anamnesis_cot)
	single_field_phase_anamnesis_generate(anamnesis_generate)
	single_field_phase_procedures_cot(procedures_cot)
	single_field_phase_procedures_generate(procedures_generate)
	single_field_phase___end__(<p>__end__</p>)
	multi_field_phase_generation_phase_case_cot_generate(case_cot_generate)
	multi_field_phase_generation_phase_case_outline_generate(case_outline_generate)
	multi_field_phase_generation_phase_patient_generate(patient_generate)
	multi_field_phase_generation_phase_chief_complaint_generate(chief_complaint_generate)
	multi_field_phase_generation_phase_anamnesis_generate(anamnesis_generate)
	multi_field_phase_generation_phase_case_checkpoint(case_checkpoint)
	multi_field_phase_generation_phase_procedures_generate(procedures_generate)
	multi_field_phase_inconsistency_phase___start__(<p>__start__</p>)
	multi_field_phase_inconsistency_phase_loop_entry(loop_entry)
	multi_field_phase_inconsistency_phase_inconsistencies_generate(inconsistencies_generate)
	multi_field_phase_inconsistency_phase_patient_refine(patient_refine)
	multi_field_phase_inconsistency_phase_chief_complaint_refine(chief_complaint_refine)
	multi_field_phase_inconsistency_phase_anamnesis_refine(anamnesis_refine)
	multi_field_phase_inconsistency_phase_procedures_refine(procedures_refine)
	multi_field_phase_inconsistency_phase_inconsistencies_none(inconsistencies_none)
	multi_field_phase_inconsistency_phase_refinement_fan_in(refinement_fan_in)
	multi_field_phase_inconsistency_phase___end__(<p>__end__</p>)
	__end__([<p>__end__</p>]):::last
	__start__ --> symptom_phase_symptoms_umls;
	multi_field_phase_inconsistency_phase___end__ --> __end__;
	single_field_phase___end__ --> __end__;
	symptom_phase_symptoms_generate -. &nbsp;single&nbsp; .-> single_field_phase_instructions_reduce;
	symptom_phase_symptoms_generate -. &nbsp;multi&nbsp; .-> multi_field_phase_generation_phase_case_cot_generate;
	subgraph symptom_phase
	symptom_phase_symptoms_umls --> symptom_phase_symptoms_generate;
	end
	subgraph single_field_phase
	single_field_phase_anamnesis_cot --> single_field_phase_anamnesis_generate;
	single_field_phase_anamnesis_generate --> single_field_phase___end__;
	single_field_phase_chiefComplaint_cot --> single_field_phase_chiefComplaint_generate;
	single_field_phase_chiefComplaint_generate --> single_field_phase___end__;
	single_field_phase_patient_cot --> single_field_phase_patient_generate;
	single_field_phase_patient_generate --> single_field_phase___end__;
	single_field_phase_procedures_cot --> single_field_phase_procedures_generate;
	single_field_phase_procedures_generate --> single_field_phase___end__;
	single_field_phase_instructions_reduce -. &nbsp;patient&nbsp; .-> single_field_phase_patient_cot;
	single_field_phase_instructions_reduce -. &nbsp;chiefComplaint&nbsp; .-> single_field_phase_chiefComplaint_cot;
	single_field_phase_instructions_reduce -. &nbsp;anamnesis&nbsp; .-> single_field_phase_anamnesis_cot;
	single_field_phase_instructions_reduce -. &nbsp;procedures&nbsp; .-> single_field_phase_procedures_cot;
	end
	subgraph multi_field_phase
	subgraph generation_phase
	multi_field_phase_generation_phase_anamnesis_generate --> multi_field_phase_generation_phase_case_checkpoint;
	multi_field_phase_generation_phase_case_cot_generate --> multi_field_phase_generation_phase_case_outline_generate;
	multi_field_phase_generation_phase_chief_complaint_generate --> multi_field_phase_generation_phase_case_checkpoint;
	multi_field_phase_generation_phase_patient_generate --> multi_field_phase_generation_phase_case_checkpoint;
	multi_field_phase_generation_phase_case_outline_generate -.-> multi_field_phase_generation_phase_patient_generate;
	multi_field_phase_generation_phase_case_outline_generate -.-> multi_field_phase_generation_phase_chief_complaint_generate;
	multi_field_phase_generation_phase_case_outline_generate -.-> multi_field_phase_generation_phase_anamnesis_generate;
	multi_field_phase_generation_phase_case_checkpoint -. &nbsp;generate&nbsp; .-> multi_field_phase_generation_phase_procedures_generate;
	end
	subgraph inconsistency_phase
	multi_field_phase_inconsistency_phase___start__ --> multi_field_phase_inconsistency_phase_loop_entry;
	multi_field_phase_inconsistency_phase_anamnesis_refine --> multi_field_phase_inconsistency_phase_refinement_fan_in;
	multi_field_phase_inconsistency_phase_chief_complaint_refine --> multi_field_phase_inconsistency_phase_refinement_fan_in;
	multi_field_phase_inconsistency_phase_inconsistencies_none --> multi_field_phase_inconsistency_phase_refinement_fan_in;
	multi_field_phase_inconsistency_phase_patient_refine --> multi_field_phase_inconsistency_phase_refinement_fan_in;
	multi_field_phase_inconsistency_phase_procedures_refine --> multi_field_phase_inconsistency_phase_refinement_fan_in;
	multi_field_phase_inconsistency_phase_refinement_fan_in --> multi_field_phase_inconsistency_phase_loop_entry;
	multi_field_phase_inconsistency_phase_loop_entry -. &nbsp;end&nbsp; .-> multi_field_phase_inconsistency_phase___end__;
	multi_field_phase_inconsistency_phase_loop_entry -. &nbsp;continue&nbsp; .-> multi_field_phase_inconsistency_phase_inconsistencies_generate;
	multi_field_phase_inconsistency_phase_inconsistencies_generate -.-> multi_field_phase_inconsistency_phase_patient_refine;
	multi_field_phase_inconsistency_phase_inconsistencies_generate -.-> multi_field_phase_inconsistency_phase_chief_complaint_refine;
	multi_field_phase_inconsistency_phase_inconsistencies_generate -.-> multi_field_phase_inconsistency_phase_anamnesis_refine;
	multi_field_phase_inconsistency_phase_inconsistencies_generate -.-> multi_field_phase_inconsistency_phase_procedures_refine;
	multi_field_phase_inconsistency_phase_inconsistencies_generate -.-> multi_field_phase_inconsistency_phase_inconsistencies_none;
	end
	multi_field_phase_generation_phase_procedures_generate --> multi_field_phase_inconsistency_phase___start__;
	end
	classDef default fill:#f2f0ff,line-height:1.2;
	classDef first fill-opacity:0;
	classDef last fill:#bfb6fc;
